version: "3.8"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      # ===================================================================== #
      # external service port range
      - "127.0.0.1:4510-4559:4510-4559"
      # ===================================================================== #
      # LocalStack Edge Proxy
      - "127.0.0.1:4566:4566"
      # ===================================================================== #
    environment:
      # ===================================================================== #
      # Reference
      # https://docs.localstack.cloud/localstack/configuration/
      # ===================================================================== #
      - DEFAULT_REGION=${DEFAULT_REGION-us-east-1}
      # ===================================================================== #
      # AWS services
      - SERVICES=${SERVICES-lambda,s3,apigateway,cloudwatch,dynamodb,sqs,kinesis,serverless,secretsmanager}
      # ===================================================================== #
      # Logging DEBUG
      - DEBUG=${DEBUG-1}
      # ===================================================================== #
      # Port number for the edge service, the main entry point for all
      # API invocations.
      - EDGE_PORT=4566
      # ===================================================================== #
      # Data is not persisted between runs, s3 Buckets contents
      # can be preserved with DATA_DIR and "/tmp/localstack" volume
      # Local directory for saving persistent data
      - DATA_DIR=${DATA_DIR-/tmp/localstack/data}
      # ===================================================================== #
    volumes:
      # ===================================================================== #
      # Data is not persisted between runs, s3 Buckets contents
      # can be preserved with DATA_DIR and "/tmp/localstack" volume
      # ===================================================================== #
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      # ===================================================================== #
      # Docker is used extensively by LocalStack, access hosts's docker
      - "/var/run/docker.sock:/var/run/docker.sock"

  # ========================================================================= #
  # AWS Glue
  # Widely used as serverless ETL
  # ========================================================================= #
  # AWS Glue Docker images are x86_64 compatible and arm64 hosts are currently
  # not supported
  aws-glue:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    container_name: "aws-glue"
    command: /home/glue_user/jupyter/jupyter_start.sh
    environment:
      - DISABLE_SSL=true
    ports:
      - "4040:4040" # Spark UI
      - "18080:18080" # Spark Submit
      - "8998:8998"
      - "8888:8888" # Jupyter UI
    links:
      - localstack
    volumes:
      - ".aws:/home/glue_user/.aws"
      - ".glue_jupyter_workspace:/home/glue_user/workspace/jupyter_workspace/"
